### ISSUE TITLE
Compatibilité emjpm

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/schema-pjm#11]
S'assurer que les données nécessaire au fonctionnement d'emjpm sont dans le schéma de données:

```json
{
   "mesures":[
      {
         "id":87243,
         "code_postal":null,
         "ville":"Paris",
         "etablissement":null,
         "mandataire_id":877,
         "created_at":"2019-10-21T09:57:36.723Z",
         "annee":"2000",
         "type":"Tutelle aux biens et à la personne",
         "date_ouverture":"2019-01-08T00:00:00.000Z",
         "residence":"En établissement",
         "civilite":"H",
         "status":"Mesure en cours",
         "extinction":null,
         "etablissement_id":null,
         "ti_id":null,
         "numero_dossier":null,
         "cabinet":null,
         "reason_extinction":null,
         "numero_rg":null,
         "department_id":71,
         "antenne_id":null,
         "service_id":null,
         "is_urgent":false,
         "judgment_date":null,
         "latitude":null,
         "longitude":null
      }
   ]
}
```

**Comment by brunolixi** [comment]
voilà qu'il faut qu'OCMI se comporte comme un éditeur
pour les mandataires qui importent depuis leur logiciel de gestion : aucun problème emjpm aura les données directement de l'éditeur
pour les mandataires (2/3 : 1400) qui utilisent OCMI directement il faut que je leur demande ces champs

**Comment by brunolixi** [comment]
OCMI ne devrait pas donner la latitude ni la longitude. ok ? et alors qu'elles sont les autres données qu'OCMI n'a pas à rassembler ; is_urgent ? c'est quoi ? c'est un dictionnaire de données sans explication, c'est un peu pénible à lire et ça peut générer des ambiguités. je n'ai pas ce type de mesure "tutelle aux biens et à la personne". il faut que je le crée à l'export ?

**Comment by tglatt** [comment]
@brunolixi , j'ai l'impression que tu ne comprends pas le fonctionnement de GitHub.

On en parlera ensemble lundi.

**Comment by tglatt** [comment]
@brunolixi, ce ticket ne te concerne pas
